### ISSUE TITLE
Average values

### ISSUE THREAD

**Issue by jotyGill** [alexbotello/python-overwatch#3]
First of all, thank you for this awesome piece of work.
I noticed the filter: average, values are not showing up properly. I think they are being rounded to "K" (1000) values.

`['Barrier Damage Done - Avg per 10 Min', '5', 'Deaths - Avg per 10 Min', '0', 'Hero Damage Done - Avg per 10 Min', '12', 'Time Spent on Fire - Avg per 10 Min', '0', 'Solo Kills - Avg per 10 Min', '0', 'Objective Time - Avg per 10 Min', '0', 'Objective Kills - Avg per 10 Min', '0', 'Healing Done - Avg per 10 Min', '4', 'Final {count, plural, one {Blow} other {Blows}} - Avg per 10 Min', '0', 'Eliminations - Avg per 10 Min', '0', 'All Damage Done - Avg per 10 Min', '17']
`

**Comment by alexbotello** [comment]
This appears to be a issue on Blizzard’s end. This library pulls the data straight down from playoverwatch.com, whatever is displayed there is what gets scraped.
